### ISSUE TITLE
Paginator not working on ReqbazRequirementsGrid component

### ISSUE THREAD

**Issue by lakhoune** [rwth-acis/RequirementsBazaar-Components#15]
It seems like the paginator is broken for the ReqbazRequirementsGrid component. In my case the page was just increasing constantly without an end even though there was only 1 requirement 
![image](https://user-images.githubusercontent.com/38857665/164036153-8f0ed77e-2cee-498a-917d-4e670ee78cd6.png)

**Comment by fxjordan** [comment]
Caused by https://github.com/rwth-acis/RequirementsBazaar/issues/155. The pagination of the API seems to be completely broken.

**Comment by fxjordan** [comment]
Should be fixed by backend update https://github.com/rwth-acis/RequirementsBazaar/releases/tag/v0.12.3 (already deployed). Can you confirm @lakhoune ?

**Comment by lakhoune** [comment]
Yes it is fixed thanks
